import IMG_01_1 from "./img/IMG_01-1.png";
import IMG_02_1 from "./img/IMG_02-1.png";
import IMG_03_1 from "./img/IMG_03-1.png";
import IMG_04_1 from "./img/IMG_04-1.png";
import IMG_05_1 from "./img/IMG_05-1.png";
import IMG_06_1 from "./img/IMG_06-1.png";
import IMG_07_1 from "./img/IMG_07-1.png";
import IMG_08_1 from "./img/IMG_08-1.png"; 
import IMG_09_1 from "./img/IMG_09-1.png"; 
import IMG_10_1 from "./img/IMG_10-1.png"; 
import IMG_11_1 from "./img/IMG_11-1.png"; 
import IMG_12_1 from "./img/IMG_12-1.png"; 

const productData = [
  {
    id: 1,
    name: "Camisa cropped laranja",
    imagem: IMG_01_1,
    color:'Laranja',
    colorHex: 'FF9A38',
    promo: "",
    valorDesconto: "",
    categoria: "Vestuário",
    price: 139.9,
    rating: 5,
    fimPromocao: 10,
    totalVendindos: 99,
  },
  {
    id: 2,
    name: "Vestido Evasê Decote V",
    imagem: IMG_02_1,
    color:'Preto',
    colorHex: '0A0608',
    promo: 29,
    valorDesconto: 119.9,
    categoria: "Vestuário",
    price: 99.9,
    rating: 4,
    fimPromocao: 4,
    totalVendindos: 52,
  },
  {
    id: 3,
    name: "Vestido Evasê Um Maria Preto",
    imagem: IMG_03_1,    
    color:'Preto',
    colorHex: '0A0608',
    promo: "",
    valorDesconto: "",
    categoria: "Vestuário",
    price: 119.9,
    rating: 4,
    fimPromocao: 12,
    totalVendindos: 40,
  },
  {
    id: 4,
    name: "Regata Feminina Folhas Preta",
    imagem: IMG_04_1,
    color:'Preto',
    colorHex: '0A0608',
    promo: "",
    valorDesconto: "",
    categoria: "Vestuário",
    price: 69.9,
    rating: 3,
    fimPromocao: 15,
    totalVendindos: 40,
  },
  {
    id: 5,
    name: "Cropped Amarração Laranja",
    imagem: IMG_05_1,
    color:'Laranja',
    colorHex: 'F2A268',
    promo: "",
    valorDesconto: "",
    categoria: "Vestuário",
    price: 139.9,
    rating: 4,
    fimPromocao: 27,
    totalVendindos: 101,
  },
 {
    id: 6,
    name: "Camiseta Boston Celtics",
    imagem: IMG_06_1,    
    color:'Cinza',
    colorHex: 'A3A6AE',
    promo:"",
    valorDesconto: "",
    categoria: "Vestuário",
    price: 69.9,
    rating: 5,
    fimPromocao: 24,
    totalVendindos: 50,
  },
  {
    id: 7,
    name: "Blusa feminina decote v branca",
    imagem: IMG_07_1,
    color:'Branca',
    colorHex: 'E7E7E7',
    promo: "",
    valorDesconto: "",
    categoria: "Vestuário",
    price: 69.9,
    rating: 4,
    fimPromocao: 23,
    totalVendindos: 88,
  },
   {
    id: 8,
    name: "Cardigan Aberto Canelado",
    imagem: IMG_08_1,
    color:'Laranja',
    colorHex: 'C44F3A',
    promo: "",
    valorDesconto: "",
    categoria: "Vestuário",
    price: 119.9,
    rating: 4,
    fimPromocao: 21,
    totalVendindos: 80,
  }, 
  {
    id: 9,
    name: "Cardigan Moletom Sem Felpa Rosa",
    imagem: IMG_09_1,
    color:'Rosa',
    colorHex: 'FF3754',
    promo: "",
    valorDesconto: "",
    categoria: "Vestuário",
    price: 119.9,
    rating: 4,
    fimPromocao: 21,
    totalVendindos: 80,
  },  
  {
  id: 10,
  name: "Suéter Tricot Lilás",
  imagem: IMG_10_1,
  color:'Lilás',
  colorHex: 'CA8F9D',
  promo: 57,
  valorDesconto: "69.9",
  categoria: "Vestuário",
  price: 29.9,
  rating: 4,
  fimPromocao: 21,
  totalVendindos: 80,
},  
   {
   id: 11,
   name: "Cardigan  Sem Felpa Marrom",
   imagem: IMG_11_1,
   color:'Marrom',
   colorHex: 'D7976E',
   promo: "",
   valorDesconto: "",
   categoria: "Vestuário",
   price: 149.9,
   rating: 4,
   fimPromocao: 21,
   totalVendindos: 80,
 },
   {
   id: 12,
   name: "Blusa Gola Alta Marrom",
   imagem: IMG_12_1,
   color:'Marrom',
   colorHex: 'A06461',
   promo: "",
   valorDesconto: "",
   categoria: "Vestuário",
   price: 69.9,
   rating: 4,
   fimPromocao: 21,
   totalVendindos: 80,
 } ,
];
export default productData;
