import IMG_01 from "./img/IMG_01.png";
import IMG_02 from "./img/IMG_02.png";
import IMG_03 from "./img/IMG_03.png";
import IMG_04 from "./img/IMG_04.png";
import IMG_01_1 from "./img/IMG_01-1.png";
import IMG_02_2 from "./img/IMG_02-1.png";
import IMG_03_3 from "./img/IMG_03-1.png";
import IMG_04_4 from "./img/IMG_04-1.png";

const productData = [
  {
    id: 1,
    name: "Camisa cropped laranja",
    imagem: IMG_01_1,
    tamanho: "M",
    promo: "",
    valorDesconto: "",
    categoria: "Vestuário",
    price: 139.9,
    rating: 5,
    fimPromocao: 10,
    totalVendindos: 99,
  },
  {
    id: 2,
    name: "Vestido Evasê Decote V",
    imagem: IMG_02_2,
    tamanho: "P",
    promo: 29,
    valorDesconto: 119.9,
    categoria: "Vestuário",
    price: 99.9,
    rating: 4,
    fimPromocao: 4,
    totalVendindos: 52,
  },
  {
    id: 3,
    name: "Vestido Evasê Um Maria Preto",
    imagem: IMG_03_3,
    tamanho: "P",
    promo: "",
    valorDesconto: "",
    categoria: "Vestuário",
    price: 119.9,
    rating: 4,
    fimPromocao: 12,
    totalVendindos: 40,
  },
  {
    id: 4,
    name: "Regata Feminina Folhas Preta",
    imagem: IMG_04_4,
    tamanho: "P",
    promo: "",
    valorDesconto: "",
    categoria: "Vestuário",
    price: 69.9,
    rating: 3,
    fimPromocao: 15,
    totalVendindos: 40,
  },
  {
    id: 13,
    name: "Blusa canelada com recorte",
    imagem: IMG_01,
    tamanho: "P",
    promo: "",
    valorDesconto: "",
    categoria: "Vestuário",
    price: 69.9,
    rating: 5,
    fimPromocao: 27,
    totalVendindos: 101,
  },
  {
    id: 14,
    name: "Blusa feminina canelada",
    imagem: IMG_02,
    tamanho: "P",
    promo:"",
    valorDesconto: "",
    categoria: "Vestuário",
    price: 79.9,
    rating: 5,
    fimPromocao: 24,
    totalVendindos: 50,
  },
  {
    id: 15,
    name: "Blusa cropped manga bufante",
    imagem: IMG_03,
    tamanho: "P",
    promo: "",
    valorDesconto: "",
    categoria: "Vestuário",
    price: 119.9,
    rating: 4,
    fimPromocao: 23,
    totalVendindos: 88,
  },
  {
    id: 16,
    name: "Jardineira Jeans Feminina",
    imagem: IMG_04,
    tamanho: "M",
    promo: "",
    valorDesconto: "",
    categoria: "Vestuário",
    price: 149.9,
    rating: 4,
    fimPromocao: 21,
    totalVendindos: 80,
  },
];
export default productData;
